# Generated by Django 4.2.6 on 2023-10-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('outlook_access_token', models.TextField(blank=True, null=True)),
                ('outlook_refresh_token', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
